### ISSUE TITLE
Erro ao cadastro de solicitante

### ISSUE THREAD

**Issue by adrianoerasmo** [carvalholeo/e-sic-livre#1]
boa noite, antes de mais nada quero agradecer por tudo que tem feito para ajudar no esic-livre.

bom, mesmo tudo correto, com a instalação e configuração. 
ainda não consigo realizar nenhum cadastro de solicitante, mesmo os dados estando corretos
no phpmailer, que pede na instalação. 
Tenho um phpmailer que já uso com os dados preenchido e funciona. Por isso digo que as configurações estão corretas no envio do e-mail.
O que posso fazer para funcionar.
Seguinte erro::: Ocorreu um erro na inclusao dos dados do Solicitante.

**Comment by carvalholeo** [comment]
Opa Adriano, boa noite, tudo bem?

Poxa, fico muito feliz em saber que alguém leu minha issue lá Portal do Software Público. Pensei que ninguém leria kkk

Considerando que o projeto original usava as funções mysql_* do PHP e que estas foram depreciadas na versão 7, as atualizações que eu fiz aqui são exclusivamente em relação à estas funções (para mysqli_*) e padronização dos comandos do MySQL.

Você está usando a versão daqui do GitHub ou a versão do GitLab do Portal SPB? Tem como ver o que está no log de erros do seu servidor Web?

Abraços!

**Comment by carvalholeo** [comment]
Entendi. Consegue ver o que há no log de erros do servidor Web
(Apache/Nginx)? Issojá pode nos ajudar a saber onde corrigir possíveis
erros.

Em sex, 27 de jul de 2018 às 19:26, adrianoerasmo <notifications@github.com>
escreveu:

**Comment by adrianoerasmo** [comment]
Agora ao ver o erro, percebir que não tem as pasta PHPMailer

**Comment by carvalholeo** [comment]
A classe do PHPMailer está na pasta class.

Em sex, 27 de jul de 2018 às 19:29, adrianoerasmo <notifications@github.com>
escreveu:

**Comment by adrianoerasmo** [comment]
Estou usando o IIS 7.5  e no log não diz nenhum erro, segue um deles:
2018-07-26 19:56:24 192.168.138.105 GET /esiclivre/cadastro/ - 59 - 177.207.2.202 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/67.0.3396.99+Safari/537.36 200 0 0 701


só mostra isso

**Comment by carvalholeo** [comment]
Certo. Vou pesquisar aqui o que está acontecendo e assim que tiver uma
resposta, me comprometo a responder por aqui mesmo. Ficamos combinados
assim?

Em sex, 27 de jul de 2018 às 19:36, adrianoerasmo <notifications@github.com>
escreveu:

**Comment by carvalholeo** [comment]
Adriano, olhando o GitLab do SPB, acabei de perceber que há uma issue sua sobre esse mesmo tópico. Chegou a ver a solução que está lá?

https://softwarepublico.gov.br/gitlab/e-sic-livre/e-sic-livre/issues/24

**Comment by adrianoerasmo** [comment]
tu acredita que funcionou.. nem acredito. e também não entendo. 
Te disse antes que tenho um phpmailer funcionando perfeitamente. mas acredita que está na porta 465.
Mas quando mudei pra a porta 587. foi tudo normal.

Nem to acreditando. Muito obrigado e parabéns. para você.  Se eu soubesse programar, eu te ajudaria
mas meu conhecimento é pouco.
Obrigado mesmo.
Valeu.

**Comment by adrianoerasmo** [comment]
Agora que deu certo, 
Ao entrar na tela inicial, quando se erra a senha a mesma pede para colocar o codigo de verificação. o mesmo está somente verde. Segue a imagem
![tela de entrada](https://user-images.githubusercontent.com/41643622/43350643-86e39fc2-91df-11e8-9782-0084b897ab92.png)

Existe em algum lugar uma área que altere os link que tem na pagina inicial. Ou tem que ser manualmente?

**Comment by carvalholeo** [comment]
Que ótimo!! 🎉🎉

Em relação ao capctha, estou com a mesma falha. O log de erros do Apache
diz pra mim que não consegue encontrar o arquivo da fonte.

Já a questão dos links, o que percebi é que é necessário alterar
manualmente em um arquivo, mas não sei dizer qual é.

Acredito que amanhã eu possa te dizer qual arquivo está com os links do
menu.

E fique despreocupado com o fato de não saber programar. Isso é só um
detalhe e em breve poderá ajudar nisso. Enquanto isso (vou até abrir uma
issue), preciso de alguém que possa escrever a documentação e verificar se
o sistema ainda está em conformidade com a LAI.



Em sex, 27 de jul de 2018 20:57, adrianoerasmo <notifications@github.com>
escreveu:

**Comment by adrianoerasmo** [comment]
Boa noite,
tudo bem.
Referente ao captcha, descobrir o que era.

essa linha deve ser comentada.

//imagedestroy($imagem); // limpa a imagem da memoria

Eu copiei o captcha do restrito e coloquei no inicial. E a diferenção só foi essa.

**Comment by adrianoerasmo** [comment]
Agora ire mexer no links, para mudar os nomes.

**Comment by carvalholeo** [comment]
AEEEEEE! Ótimo!

Obrigado por sinalizar e fechar a issue. Vou fechar a issue #2 sobre o erro da captcha também.
