### ISSUE TITLE
Sobre adequação a LAI, Método de login.

### ISSUE THREAD

**Issue by lgdelai** [carvalholeo/e-sic-livre#13]
Parece que estão pegando na questão de ter que fazer cadastro para fazer a solicitação. 

Em alguns sistemas, a cada solicitação, é criado automaticamente um código que numera a solicitação, e um código de acesso (senha). 

Assim o solicitante pode verificar sua solicitação com estes códigos em mãos. 

Estava pensando em adaptar o sistema de login atual para funcionar desta forma. 

Assim para fazer a solicitação a pessoa não precisaria se cadastrar, ele faria normalmente e receberia os códigos de acesso para acompanhar. 

O que acha?

**Comment by vinnyparker** [comment]
encontrei a mesma situação, de nao obrigar  o cadastro.
