### ISSUE TITLE
Erro na geração do código captcha

### ISSUE THREAD

**Issue by carvalholeo** [carvalholeo/e-sic-livre#3]
Estamos com um erro no código do sistema, na parte de login.

Tanto na área administrativa quanto na área aberta, se houver um erro no login, aparece a caixa solicitando o captcha. No entanto, o código não é mostrado, apenas uma caixa preta (ou verde) aparece.

No log do Apache, é indicado que o arquivo da fonte não está disponível na pasta, mesmo com o arquivo estando lá (mesmo nome e extensão de arquivo, em letras minúsculas, que está na definição da função).

Não faço ideia do que possa estar causando esta falha e sem o código também não é possível acessar a página.

**Comment by adrianoerasmo** [comment]
Conseguir retirando o comentario que limpa a memoria do.

Peguei o captcha qu estava no restrito e colocou na pagina e deu certo.

**Comment by carvalholeo** [comment]
Opa, ótimo!

Vou atualizar o arquivo no repositório local e já jogo no GitHub.
Talvez eu demore um pouco, devido a troca de sistema operacional que estou fazendo. Muito obrigado pela ajuda.
